flowchart LR
  Platform[ORISO Platform Super Graph]
  Platform --> ORISO_Frontend[ORISO-Frontend<br/>1967 nodes / 4204 edges]
  Platform --> ORISO_Admin[ORISO-Admin<br/>776 nodes / 1547 edges]
  Platform --> ORISO_UserService[ORISO-UserService<br/>2295 nodes / 3854 edges]
  Platform --> ORISO_AgencyService[ORISO-AgencyService<br/>623 nodes / 835 edges]
  Platform --> ORISO_ConsultingTypeService[ORISO-ConsultingTypeService<br/>470 nodes / 515 edges]
  Platform --> ORISO_TenantService[ORISO-TenantService<br/>380 nodes / 623 edges]
  Platform --> ORISO_Database[ORISO-Database<br/>192 nodes / 312 edges]
  Platform --> ORISO_Keycloak[ORISO-Keycloak<br/>152 nodes / 247 edges]
  Platform --> ORISO_Kubernetes[ORISO-Kubernetes<br/>339 nodes / 588 edges]
